### ISSUE TITLE
Xcode Bug

### ISSUE THREAD

**Issue by LoftyNine7** [LoftyNine7/Cydeload#3]
Xcode is unusable when the device is in a jailbroken state.

**Comment by jakeajames** [comment]
Reason for this:

kppless mounts a new volume inside of /Developer. /Developer is reserved by Xcode therefore it will fail to attach debugging.

**Comment by LoftyNine7** [comment]
Fixed by not mounting /Developer as RO (extra_recipe already did this and the mount would succeed because we already have rw over /Developer AFAIK), but thanks for bringing up /Developer.
